server:
  port: 8085
spring:
  application:
    name: travel-chart-search
  config:
    import: optional:nacos:travel-chart-search.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        import-check:
          enabled: false
        server-addr: localhost:8848
        namespace: public
        file-extension: yaml
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-consumer-group

jwt:
  secret: travel-chart-jwt-secret-key-2024
