server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: travel-chart-social
  config:
    import: optional:nacos:travel-chart-social.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        import-check:
          enabled: false
        server-addr: localhost:8848
        namespace: public
        file-extension: yaml


